### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by Nchedubem**
please kindly review my work
@Promise-J
@ChidiPatrick
Group A

### CODE REVIEW

**Review by promise-J — CHANGES_REQUESTED** [review]
Great work. please add a padding in the .cohort  .content .text-container to shift them from touching the parent and do the same for the section.jp .content .text-container
Once you do this, please proceed to merge

**Review by promise-J — CHANGES_REQUESTED** [review]
Great work. please add a padding in the .cohort  .content .text-container to shift them from touching the parent and do the same for the section.jp .content .text-container
Once you do this, please proceed to merge

**Review by promise-J — CHANGES_REQUESTED** [review]
Great work. please add a padding in the .cohort  .content .text-container to shift them from touching the parent and do the same for the section.jp .content .text-container
Once you do this, please proceed to merge

**Review by promise-J — CHANGES_REQUESTED** [review]
Great work. please add a padding in the .cohort  .content .text-container to shift them from touching the parent and do the same for the section.jp .content .text-container
Once you do this, please proceed to merge

**Review by promise-J — CHANGES_REQUESTED** [review]
Make sure to add some padding around the text containers in both the Jp section and the cohort. Make the links in the header disappears too when they become too congested. You had a very great work here @Nchedubem

**Comment by Nchedubem** [comment]
I have done the correction

**Review by promise-J — CHANGES_REQUESTED** [review]
You didn't effect the changes. Padding in the text containers, hide nav links when you see the get congested and the site generally is not looking great. To see my point better, please view the work on your mobile phone

**Comment by Nchedubem** [comment]
Done.

**Comment by promise-J** [comment]
@Nchedubem, this is far from done. Please view it on the phone screen and see what you have. Correct it please

**Pull request merged**
